config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :profiles, only: [:edit, :update]
  resources :destinations, only: [:edit, :update]
  devise_scope :user do
    get '/users/show', to: 'users/sessions#show'
    get '/users/putting_up_list', to: 'users/sessions#putting_up_list'
    get '/users/completed_item', to: 'users/sessions#completed_item'
    get '/users/favorite_item', to: 'users/sessions#favorite_item'
    get '/users/payment_method', to: 'users/sessions#payment_method'
    get '/users/logout', to: 'users/sessions#logout'
  end

  root 'items#top'
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'top'
      get 'payment_method'
      get 'thanks'
      post 'favorite', defaults: { format: 'json' }
    end
    member do
      get 'buy'
      post 'pay'
    end
  end
  resources :credit_cards, only: [:create, :new, :show, :destroy] do
    collection do
      get 'redirect_back'
    end
  end
  resources :categories, only: [:index, :show] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/categories_size.rb
class CategoriesSize < ApplicationRecord
  belongs_to :category
  belongs_to :size
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
  has_many :categories_sizes
  has_many :sizes, through: :categories_sizes
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  validates :card_id, presence: { message: "%{attribute} を入力してください" }
  validates :customer_id, presence: { message: "%{attribute} を入力してください" }
  validates :user_id, presence: { message: "%{attribute} を入力してください" }
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user, inverse_of: :destination
  validates :first_name, :family_name, :first_name_kana, :family_name_kana,  :postal_code, :house_number,  :phone_number, presence: true
  validates :first_name, :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :family_name_kana, :first_name_kana, format: { with: /\A[ァ-ヴ]+\z/ }
  validates :postal_code, format: { with: /\A\d{7}\z/ }
  validates :phone_number, format: { with: /\A0[0-9]{9,10}\z/ }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  validates_associated :item_images

  belongs_to :category
  belongs_to :size, optional: true
  belongs_to :brand, optional: true
  belongs_to_active_hash :item_condition
  belongs_to_active_hash :postage_payer
  belongs_to_active_hash :preparation_day
  belongs_to_active_hash :status
  belongs_to :user
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :introduction
    validates :price, numericality: {only_integer: true}
    validates :category_id
    validates :item_images
    validates :item_condition_id
    validates :postage_payer_id
    validates :preparation_day_id
    validates :prefecture_code
    validates :user_id
  end
end

app/models/item_condition.rb
class ItemCondition < ActiveHash::Base
  self.data = [
    { id: 1, name: '新品、未使用' },
    { id: 2, name: '未使用に近い' },
    { id: 3, name: '目立った傷や汚れなし' },
    { id: 4, name: 'やや傷や汚れあり' },
    { id: 5, name: '傷や汚れあり' },
    { id: 6, name: '全体的に状態が悪い' }
  ]
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item
  mount_uploader :url, ImageUploader
end

app/models/postage_payer.rb
class PostagePayer < ActiveHash::Base
  self.data = [
    { id: 1, name: '送料込み(出品者負担)' },
    { id: 2, name: '着払い(購入者負担)' }
  ]
end

app/models/preparation_day.rb
class PreparationDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '1〜2日で発送' },
    { id: 2, name: '2〜3日で発送' },
    { id: 3, name: '4〜7日で発送' }
  ]
end

app/models/profile.rb
class Profile < ApplicationRecord
belongs_to :user, inverse_of: :profile
validates :first_name, :family_name, :family_name_kana, :first_name_kana, :birth_date, presence: true

validates :family_name_kana, :first_name_kana, format: { with: /\A[ァ-ヴ]+\z/ }
validates :first_name, :family_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_ancestry
  has_many :categories_sizes
  has_many :categories, through: :categories_sizes
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '出品中' },
    { id: 2, name: '売却済' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  validates :email, uniqueness: {case_sensitive: true}, format: { with: /\A([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+\z/ }
  validates :password, presence: true, length: { minimum: 7 }
  has_many :items, dependent: :destroy
  has_one :profile, dependent: :destroy, inverse_of: :user
  has_one :destination, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :destination
  accepts_nested_attributes_for :profile
  include JpPrefecture
  jp_prefecture :prefecture_code
  has_many :items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  def new
    card = CreditCard.where(user_id: current_user.id)
    redirect_to credit_card_path(card) if card.exists?
  end

  def create
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
    if params[:token].blank?
      flash.now[:alert] = "保存できませんでした。カード情報を確認の上、再度入力してください。".html_safe
      render :new
    else
      customer = Payjp::Customer.create(
        card: params[:token]
      )
      @card = CreditCard.new(
        card_id: customer.default_card,
        customer_id: customer.id,
        user_id: current_user.id
      )
      if @card.save
        card = CreditCard.where(user_id: current_user.id)
        redirect_to credit_card_path(card)
      else
        flash.now[:alert] = "保存できませんでした。カード情報を確認の上、再度入力してください。".html_safe
        render :new
      end
    end
  end

  # Cardのデータをpayjpに送り情報を取り出して表示
  def show
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to new_credit_card_path
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_info = customer.cards.retrieve(card.card_id)
    end
  end

  # PayjpとCardデータベースを削除
  def destroy
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_back
  end

  # 記憶したURLにリダイレクト
  def redirect_back
    redirect_to(session[:forwarding_url])
    session.delete(:forwarding_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/credit_cards/new.html.haml
.CardRegistPage
  #CardRegistHeader
    %h1
      = link_to image_tag('logo.png', size: "214x62", alt: "FURIMA"), root_path
  #CardRegistArea
    %h2 新規カード登録
    .FormArea
      = form_with url: credit_cards_path, id: "regist-form", local: true do |form|
        .FormItem
          %dl
            %dt.FormItem__label
              = form.label :number, "カード番号"
              %span.required 必須
            %dd.FormItem__detail
              = form.text_field :number, class: "form_detail", placeholder: "半角数字のみ", maxlength: "16", required: true, onInput: "value = value.replace(/[^0-9]+/i,'')"
            %dd.FormItem__note
              VISA / MASTERCARD / JCB / AMEX / DINERS / DISCOVER
        .FormItem
          %dl
            %dt.FormItem__label
              = form.label :exp_date, "有効期限"
              %span.required 必須
            %dd.FormItem__detail.FormItem__exp_date
              = form.text_field :exp_month, class: "exp_month", placeholder: "例）09", maxlength: "2", required: true, onInput: "value = value.replace(/[^0-9]+/i,'')"
              %p 月&nbsp;／
              = form.text_field :exp_year, class: "exp_year", placeholder: "例）2020", maxlength: "4", required: true, onInput: "value = value.replace(/[^0-9]+/i,'')"
              %p 年
        .FormItem
          %dl
            %dt.FormItem__label
              = form.label :cvc, "セキュリティコード"
              %span.required 必須
            %dd.FormItem__detail
              = form.text_field :cvc, class: "form_detail", placeholder: "カード背面3桁または4桁の数字", maxlength: "4", required: true, onInput: "value = value.replace(/[^0-9]+/i,'')"
        .formItem
          %p.FormItem__btn
            = form.submit "登録する", class: "card_submit_btn"
            = link_to "もどる", :back
  #CardRegistFooter
    %h2
      = image_tag "logo.png", size: "107x31", alt: "FURIMA"
    %p &copy; FURIMA

app/views/credit_cards/show.html.haml
.CardShowPage
  #CardShowHeader
    %h1
      = link_to image_tag('logo.png', size: "214x62", alt: "FURIMA"), root_path
  #CardShowArea
    %h2 登録情報
    .ShowArea
      .Card
        .Card__detail
          %dl
            %dt.Card__detail__label
              クレジットカード
            %dd.Card__detail__contents
              = "**** **** **** #{@default_card_info.last4}"
            %dd.Card__detail__contents
              = "有効期限 #{@default_card_info.exp_month} / #{@default_card_info.exp_year}"
        .Card__deleteBtn
          = link_to "削除する", credit_card_path(@default_card_info.id), method: :delete, class: "btn"
      .Button.border
        %p.Button__btn
          = link_to "このカードを使う", {controller: 'credit_cards', action: 'redirect_back'}
          -# = link_to "トップページへ", root_path
          -# %p.Button__back
          -#   = link_to "もどる", :back
  #CardShowFooter
    %h2
      = image_tag "logo.png", size: "107x31", alt: "FURIMA"
    %p &copy; FURIMA