config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :profiles, only: [:edit, :update]
  resources :destinations, only: [:edit, :update]
  devise_scope :user do
    get '/users/show', to: 'users/sessions#show'
    get '/users/putting_up_list', to: 'users/sessions#putting_up_list'
    get '/users/completed_item', to: 'users/sessions#completed_item'
    get '/users/favorite_item', to: 'users/sessions#favorite_item'
    get '/users/payment_method', to: 'users/sessions#payment_method'
    get '/users/logout', to: 'users/sessions#logout'
  end

  root 'items#top'
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'top'
      get 'payment_method'
      get 'thanks'
      post 'favorite', defaults: { format: 'json' }
    end
    member do
      get 'buy'
      post 'pay'
    end
  end
  resources :credit_cards, only: [:create, :new, :show, :destroy] do
    collection do
      get 'redirect_back'
    end
  end
  resources :categories, only: [:index, :show] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  validates_associated :item_images

  belongs_to :category
  belongs_to :size, optional: true
  belongs_to :brand, optional: true
  belongs_to_active_hash :item_condition
  belongs_to_active_hash :postage_payer
  belongs_to_active_hash :preparation_day
  belongs_to_active_hash :status
  belongs_to :user
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :introduction
    validates :price, numericality: {only_integer: true}
    validates :category_id
    validates :item_images
    validates :item_condition_id
    validates :postage_payer_id
    validates :preparation_day_id
    validates :prefecture_code
    validates :user_id
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_root, only: [:new, :edit]
  before_action :correct_user, only: [:destroy, :edit, :update]
  before_action :set_item, only: [:edit, :update, :show, :destroy, :buy, :pay, :favorite]
  before_action :set_category, only: [:edit, :update]

  def top
    @new_items = Item.where(status_id: 1).order(created_at: :desc).limit(5)
  end

  def index
  end

  def new
    @item = Item.new
    @item.item_images.new
    @categories = Category.where(ancestry: nil)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: "商品を出品しました"
    else
      if @item.category != nil
        set_category
        if @item.size !=nil
          @sizes = @item.size.siblings
        end
      end
      @item.item_images.new
      @categories = Category.where(ancestry: nil)
      render :new
    end
  end
  
  def show
    category = Category.find(@item.category_id)
    # 「もっと見る」表示用のインスタンス
    @more_items = category.items.where(status_id: 1).where.not(id: @item.id).order(created_at: :desc).limit(5)
    # 「前の商品」「後ろの商品」表示用のインスタンス
    @items = category.items.where(status_id: 1)
    @favorite_number = Favorite.where(item_id: @item.id).length
    # current_userのいいねが存在するかどうか
    if user_signed_in?
      @exist_favorite = Favorite.find_by(item_id: @item.id, user_id: current_user.id).blank?
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def buy
    store_location
    if user_signed_in?
      @user = current_user.destination
      @card = CreditCard.where(user_id: current_user.id).first
      unless @card.blank?
        Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @default_card_info = customer.cards.retrieve(@card.card_id)
      end
      @pref = JpPrefecture::Prefecture.find(@user.prefecture_code)
    else
      redirect_to new_user_session_path
    end
  end

  # 登録したカードで支払い
  def pay
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to new_credit_card_path
    else
      Payjp.api_key = Rails.application.credentials[:payjp][:secret_key]
      Payjp::Charge.create(
        amount: @item.price,
        customer: card.customer_id, 
        currency: 'jpy'
      )
      @item.update(status_id: '2')
      redirect_to thanks_items_path
    end
  end

  def thanks
  end
  
  def edit
    if @item.size !=nil
      @sizes = @item.size.siblings
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(params[:id]), notice: "商品情報を変更しました"
    else
      if @item.size !=nil
        @sizes = @item.size.siblings
      end
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: "出品を取り消しました"
    else
      redirect_to root_path, alert: "エラーが発生しました"
    end
  end

  def favorite
    exist_favorite = Favorite.find_by(item_id: @item.id, user_id: current_user.id)
    if exist_favorite == nil
      Favorite.create(item_id: @item.id, user_id: current_user.id)
    else
      exist_favorite.destroy
    end
    @favorite_number = Favorite.where(item_id: @item.id).length
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :category_id, :size_id, :brand_id,:item_condition_id, :postage_payer_id, :prefecture_code, :preparation_day_id, :status_id, item_images_attributes: [:url, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def move_to_root
    redirect_to action: :top unless user_signed_in?
  end

  def correct_user
    seler_user = Item.find(params[:id]).user
    redirect_to(root_path) unless seler_user == current_user
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_category
    @category = @item.category
    # 登録カテゴリーが子の場合か孫の場合で分岐
    if @category.ancestors.length == 1 
      @categories_child = @category.siblings
      @categories_parent = @category.parent.siblings
    else 
      @categories_parent = @category.parent.parent.siblings
      @categories_child = @category.parent.siblings
      @categories_grandchild = @category.siblings
    end
  end

  def order_params
    params.permit(:token)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
%footer
  .footer_container
    .footer_list
      .Footer_content
        %h2.Footer_content__headline FURIMAについて
        %ul.Footer_content__list
          .Footer_content__list__link_wrapper
            = link_to "会社概要（運営会社）", "#", class: "Footer_content__list__link"
          .Footer_content__list__link_wrapper
            = link_to "プライバシーポリシー", "#", class: "Footer_content__list__link"
          .Footer_content__list__link_wrapper
            = link_to "FURIMA利用規約", "#", class: "Footer_content__list__link"
          .Footer_content__list__link_wrapper
            = link_to "ポイントに関する特約", "#", class: "Footer_content__list__link"
      .Footer_content
        %h2.Footer_content__headline FURIMAを見る
        %ul.Footer_content__list
          .Footer_content__list__link_wrapper
            = link_to "カテゴリー一覧", categories_path, class: "Footer_content__list__link"
          .Footer_content__list__link_wrapper
            = link_to "ブランド一覧", "#", class: "Footer_content__list__link"
      .Footer_content
        %h2.Footer_content__headline ヘルプ＆ガイド
        %ul.Footer_content__list
          .Footer_content__list__link_wrapper
            = link_to "FURIMAガイド", "#", class: "Footer_content__list__link"
          .Footer_content__list__link_wrapper
            = link_to "FURIMAロゴ利用ガイドライン", "#", class: "Footer_content__list__link"
          .Footer_content__list__link_wrapper
            = link_to "お知らせ", "#", class: "Footer_content__list__link"
    = link_to "/" do
      = image_tag "logo/logo-white.png", class:"footer_logo", size:"160x46"
    %p.footer_copy © FURIMA

app/views/items/_header.html.haml
%body
  %header
    .header_container
      .header_main
        = link_to "/" do
          = image_tag 'logo/logo.png', class: "header_logo", size: "140x41"
        = form_with url: "#", class: "Search" do |f|
          = f.text_field :search, class: "Search__form", placeholder: "キーワードから探す"
          %label.Search__btn
            .Search__btn__icon_wrapper
              = image_tag 'icon/icon-search 1.png', size: "20x20", class: "Search__btn__icon"
            = f.submit "btn", class: "Search__btn__submit"
      .header_navs
        %ul.Header_nav_left
          = link_to "カテゴリー", categories_path, class: "Header_nav_left__list", id: "category_nav"
          = link_to "ブランド", "#", class: "Header_nav_left__list"
        %ul.Header_nav_right
          - unless user_signed_in?
            = link_to "ログイン", new_user_session_path, class: "Header_nav_right__list"
            = link_to "新規会員登録", new_user_registration_path, class: "Header_nav_right__list"
          - else
            = link_to "マイページ", users_show_path, class: "Header_nav_right__list"
            = link_to "ログアウト", users_logout_path, class: "Header_nav_right__list"
        .category_nav_box
          .parent_nav_box
          .child_nav_box
          .grandchild_nav_box

app/views/items/_items_list.html.haml
= link_to item_path(item.id), class: "Item_box" do
  = image_tag "#{item.item_images.first.url}", class: "Item_box__img", size:"180x180"
  .Item_box__text_block
    %h3.Item_box__text_block__item_name= item.name
    .Item_box__text_block__price ¥ #{item.price}
    - unless item.favorites.length == 0
      %dl.Item_box__text_block__favorite
        - if user_signed_in? && Favorite.find_by(user_id: current_user.id, item_id: item.id)
          %dt.Item_box__text_block__favorite--icon= icon("fas", "star")
        - else
          %dt.Item_box__text_block__favorite--icon= icon("far", "star")
        %dd.Item_box__text_block__favorite--num #{item.favorites.length}

app/views/items/_putting_up_btn.html.haml
= link_to new_item_path, class:"Listing_btn" do
  %p.Listing_btn__text 出品する
  = image_tag "icon/icon_camera.png", class:"Listing_btn__icon", size:"54x54"

app/views/items/buy.html.haml
-# - if user_signed_in?
.BuyPage
  #BuyHeader
    %h1
      = link_to image_tag('logo.png', size: "214x62", alt: "FURIMA"), root_path
  #BuyArea
    %h2 購入内容の確認
    .ItemDetail.BuyAreaBox
      .ItemDetail__image
        = image_tag "#{@item.item_images.first.url}", class: "ItemImage", size: "100x100", alt: "ItemImage"
      .ItemDetail__text 
        .ItemDetail__text__name
          = @item.name
        .ItemDetail__text__price
          送料込み（税込）
          %span= "¥#{@item.price}"
    .PaymentAmount.BuyAreaBox
      %dl.PaymentAmount__detail
        %dt.PaymentAmount__detail__title 支払い金額
        %dd.PaymentAmount__detail__price= "¥#{@item.price}"
    .PaymentMethod.BuyAreaBox
      - if @card.blank?
        %dl.PaymentMethod__detail
          %dt 支払い方法
          %dd
            =icon('far', 'plus-square')
            = link_to 'クレジットカードを登録して下さい', new_credit_card_path
      - else
        %dl.PaymentMethod__detail
          %dt 支払い方法
          %dd
            %dl
              %dt クレジットカード
              %dd
                = "**** **** **** #{@default_card_info.last4}"
              %dd
                = "有効期限 #{@default_card_info.exp_month} / #{@default_card_info.exp_year}"
        .PaymentMethod__changeBtn
          = link_to "変更する", credit_card_path(@card), class: "btn"
    #Destination.BuyAreaBox
      %dl
        %dt 配送先
        %dd
          = current_user.destination.postal_code
          %br
            ="#{@pref.name} #{@user.city} #{@user.house_number}"
          - if @user.room_number.blank?
          - else
            %br
            = @user.room_number
    #BuyBtn.BuyAreaBox
      - if @card.blank?
        %p.alert 支払い方法を登録してください
        %p.btn 購入する
      - elsif @user.blank?
        %p.alert ログインしてください
        %p.btn 購入する
      - else
        = form_with url: pay_item_path, local: true do |form|
          = form.submit "購入する", class: 'btn', name: 'kounyuu'
  #BuyFooter
    %h2
      = image_tag "logo.png", size: "107x31", alt: "FURIMA"
    %p &copy; FURIMA
-# - else

app/views/items/edit.html.haml
.SettingExhibitionForm
  #FormHeader
    %h1
      = link_to image_tag('logo.png', size: "214x62", alt: "FURIMA"), root_path
  .FormArea
    = form_with model: @item, local: true do |form|
      .FormItem
        %dl
          %dt.FormItem__label
            = form.label :name, "商品画像"
            %span.required 必須
          %dd.FormItem__imagebox
            #previews
              - if @item.persisted?
                - @item.item_images.each_with_index do |image, i|
                  .preview
                    = image_tag image.url.to_s, data: { index: i }, width: "200", height: '200'
                    %span.js-remove 削除
              = form.fields_for :item_images do |i|
                .js-file_group{data: {index: i.index}}
                  %label 
                    = icon("fas", "camera-retro")
                    = i.file_field :url, class: 'js-file'
                - if @item.persisted?
                  = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
              - if @item.persisted?
                .js-file_group{data: {index: @item.item_images.count}}
                  %label
                    = icon("fas", "camera-retro")
                    = file_field_tag :url, name: "item[item_images_attributes][#{@item.item_images.count}][url]", class: 'js-file'
        - if @item.errors.include?(:item_images)
          .FormItem__error_message 商品画像をアップロードしてください
      .FormItem.border
        %dl
          %dt.FormItem__label
            = form.label :name, "商品名"
            %span.required 必須
          %dd.FormItem__detail
            = form.text_field :name, class: "form_detail"
        - if @item.errors.include?(:name)
          .FormItem__error_message 商品名を入力してください
      .FormItem
        %dl
          %dt.FormItem__label
            = form.label :introduction, "商品の説明"
            %span.required 必須
          %dd.FormItem__detail
            = form.text_area :introduction, rows: 6, class: "form_detail"
        - if @item.errors.include?(:introduction)
          .FormItem__error_message 商品説明を入力してください
      .FormItem.border#Category__form
        %dl
          %dt.FormItem__label
            = form.label :category, "カテゴリー"
            %span.required 必須
          -# 登録カテゴリーが子の場合か孫の場合で分岐
          - if @category.ancestors.length == 1 
            %dd.FormItem__detail#Parent__form
              = form.collection_select(:category_id, @categories_parent, :id, :name, {prompt: '選択してください', selected: @category.parent_id}, {class: "Parent__form--content"})
            %dd.FormItem__detail#Child__form
              = form.collection_select(:category_id, @categories_child, :id, :name, {prompt: '選択してください', selected: @category.id}, {required: true, class: "Child__form--content"})
          - else
            %dd.FormItem__detail#Parent__form
              = form.collection_select(:category_id, @categories_parent, :id, :name, {prompt: '選択してください', selected: @category.parent.parent_id}, {class: "Parent__form--content"})
            %dd.FormItem__detail#Child__form
              = form.collection_select(:category_id, @categories_child, :id, :name, {prompt: '選択してください', selected: @category.parent_id}, {required: true, class: "Child__form--content"})
            %dd.FormItem__detail#GrandChild__form
              = form.collection_select(:category_id, @categories_grandchild, :id, :name, {prompt: '選択してください'}, {required: true, class: "GrandChild__form--content"})
        - if @item.errors.include?(:category)
          .FormItem__error_message カテゴリーを選択してください
      -# サイズが登録してあるか？
      - if @item.size != nil
        .FormItem#Size__form
          %dl
            %dt.FormItem__label
              = form.label :size, "サイズ"
              %span.required 必須
            %dd.FormItem__detail
              = form.collection_select(:size_id, @sizes, :id, :name, {prompt: '選択してください'}, {class: "Size__form--content"})
      .FormItem
        %dl
          %dt.FormItem__label
            = form.label :brand, "ブランド"
            %span.any 任意
          -# 余裕があればインクリメンタルサーチでブランド検索実装、現状はbrandを数個用意してプルダウンで選択
          %dd.FormItem__detail
            = form.collection_select(:brand_id, Brand.find(1,2,3), :id, :name, {prompt: '選択してください'}, {})
      .FormItem
        %dl
          %dt.FormItem__label
            = form.label :item_condition, "商品の状態"
            %span.required 必須
          %dd.FormItem__detail
            = form.collection_select(:item_condition_id, ItemCondition.all, :id, :name, {prompt: '選択してください'}, {})
        - if @item.errors.include?(:item_condition_id)
          .FormItem__error_message 商品の状態を選択してください
      .FormItem.border
        %dl
          %dt.FormItem__label
            = form.label :postage_payer, "配送料の負担"
            %span.required 必須
          %dd.FormItem__detail
            = form.collection_select(:postage_payer_id, PostagePayer.all, :id, :name, {prompt: '選択してください'}, {})
        - if @item.errors.include?(:postage_payer_id)
          .FormItem__error_message 配送料の負担を選択してください
      .FormItem
        %dl
          %dt.FormItem__label
            = form.label :prefecture_code, "発送元の地域"
            %span.required 必須
          %dd.FormItem__detail
            = form.collection_select(:prefecture_code, JpPrefecture::Prefecture.all, :code, :name, {prompt: "選択してください"}, {})
        - if @item.errors.include?(:prefecture_code)
          .FormItem__error_message 発送元の地域を選択してください
      .FormItem
        %dl
          %dt.FormItem__label
            = form.label :preparation_day, "発送までの日数"
            %span.required 必須
          %dd.FormItem__detail
            = form.collection_select(:preparation_day_id, PreparationDay.all, :id, :name, {prompt: '選択してください'}, {})
        - if @item.errors.include?(:preparation_day_id)
          .FormItem__error_message 発送までの日数を選択してください
      .FormItem.border
        %dl
          %dt.FormItem__label
            = form.label :price, "価格 （¥300 ~）"
            %span.required 必須
          %dd.FormItem__detail.FormItem__price--form
            = form.text_field :price, class: "form_detail", id: "FormItem__price--form_val"
        - if @item.errors.include?(:price)
          .FormItem__error_message 価格を入力してください
        .FormItem__price
          販売手数料 (10%)
          %span ¥
          .FormItem__price--fee_val
            ー
        .FormItem__price
          販売利益
          %span ¥
          .FormItem__price--profit_val
            ー
      .FormItem
        = form.hidden_field :status_id, value: 1
      .formItem 
        %p.FormItem__btn
          = form.submit "変更する"
  #FormFooter
    %h2
      = image_tag "logo.png", size: "107x31", alt: "FURIMA"
    %p &copy; FURIMA

app/views/items/show.html.haml
= render partial: "header"

.itemshow_wrapper
  .itemInfoBox
    %h1.itemInfoBox__itemName= @item.name
    = image_tag "#{@item.item_images.first.url}", class: "itemInfoBox__mainImage"
    .itemInfoBox__allImageBox
      - @item.item_images.each do |image|
        = image_tag "#{image.url}", class: "itemInfoBox__allImageBox__subImages", data: {url: "#{image.url}" }
    %p.itemInfoBox__itemPrice= "#{@item.price}円"
    %p.itemInfoBox__priceTax （税込）送料込み
    %p.itemInfoBox__itemIntroduction= @item.introduction
    %table.itemInfoBox__itemInfoTable{border: "1"}
      %tr
        %td.leftColumn 出品者
        %td.rightColumn= @item.user.nickname
      %tr
        %td.leftColumn カテゴリー
        %td.rightColumn
          - if @item.category.has_parent? && @item.category.parent.has_parent?
            %div=link_to "#{@item.category.parent.parent.name}", category_path(@item.category.parent.parent.id)
          - if @item.category.has_parent?
            %div=link_to "#{@item.category.parent.name}", category_path(@item.category.parent.id)
          %div=link_to "#{@item.category.name}", category_path(@item.category.id)
      %tr
        %td.leftColumn ブランド名
        %td.rightColumn
          - if @item.brand_id
            = @item.brand.name
      %tr
        %td.leftColumn 商品のサイズ
        %td.rightColumn
          - if @item.size_id
            = @item.size.name
      %tr
        %td.leftColumn 商品の状態
        %td.rightColumn= @item.item_condition.name
      %tr
        %td.leftColumn 配送料の負担
        %td.rightColumn= @item.postage_payer.name
      %tr
        %td.leftColumn 発送元の地域
        %td.rightColumn= JpPrefecture::Prefecture.find(@item.prefecture_code).name
      %tr
        %td.leftColumn 発送日の目安
        %td.rightColumn= @item.preparation_day.name
    .itemInfoBox__btnBox
      = link_to "#", class:"favoriteBtn" do
        = icon "fas", "star" , class: "favoriteIcon"
        %p.favoriteBtnText お気に入り 1
      = link_to "#", class: "reportBtn" do
        = icon "fas", "flag", class: "reportIcon"
        %p 不適切な商品の通報

  - if @item.status_id == 1
    - if current_user && current_user.id == @item.user.id
      .editorBox
        -# %p.editorBox__headline 出品者編集
        .editorBox__btnBox
          = link_to "商品情報編集", edit_item_path, class: "editorBtn edit"
          = link_to "出品取消", "#", class: "editorBtn delete", method: :delete
    - else
      .purchaseBox
        = link_to "購入する", buy_item_path(@item.id), class: "purchaseBtn"

    .commentBox
      = form_with url: "#", class: "commentForm" do |f|
        = f.text_area :content, class: "commentForm__content", rows: "5"
        %p.commentForm__attention 
          相手のことを考え丁寧なコメントを心がけましょう。
          %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %label
          = f.submit "送信", class: "commentForm__submitBtn"
          .commentForm__btnLooking
            = icon "fas", "comment", class: "speechBubbleIcon"
            %p コメントする
    .fowardAndNextBtnBox
      - if (@items.index(@item)-1) >= 0
        = link_to "〈 前の商品", item_path(@items[(@items.index(@item))-1].id), class: "fowardAndNextBtnBox__fowardBtn"
      - if @items[(@items.index(@item))+1]
        = link_to "後ろの商品 〉", item_path(@items[(@items.index(@item))+1].id), class: "fowardAndNextBtnBox__nextBtn"
    .moreItemsShowBox
      = link_to "#{@item.category.name}をもっと見る", category_path(@item.category_id), class: "moreItemsShowBox__headline"
      .moreItemsShowBox__itemList
        = render partial: "items_list", collection: @more_items, as: "item"

= render partial: "footer"

app/views/items/thanks.html.haml
.ThanksPage
  #ThanksHeader
    %h1
      = link_to image_tag('logo.png', size: "214x62", alt: "FURIMA"), root_path
  #ThanksArea
    %h2 購入完了
    .MessageArea
      %p.MessageArea__image
        =icon('fas', 'gifts')
      %p.MessageArea__message
        %span
          Congratulations!
        %br
        購入が完了しました
    .Button
      %p.Button__btn
        = link_to "トップページへ", root_path
  #ThanksFooter
    %h2
      = image_tag "logo.png", size: "107x31", alt: "FURIMA"
    %p &copy; FURIMA

app/views/items/top.html.haml
= render partial: "header"
.main_visual_section
  .Main_visual
    %h1.Main_visual__headline 人生を変えるフリマアプリ
    %p.Main_visual__text
      FURIMAはだれでもかんたんに出品・購入できる
      %br>/
      フリマアプリです
    .Main_visual__badge
      = link_to "#" do
        = image_tag 'badge/app_store_badge.png', class: "Main_visual__badge--apple", size: "180x53"
      = link_to "#" do
        = image_tag 'badge/google-play-badge.png', class: "Main_visual__badge--google", size: "180x53"
.strong_point_section
  .Strong_point_list
    %h2.Strong_point_list__headline FURIMAが選ばれる3つの理由
    .Strong_point_list__reason_list
      .Reason_box
        .Reason_box__image_box
          = image_tag 'pict/pict-reason-01.jpg', class: "Reason_box__image_box__img"
          .Reason_box__image_box__number 1
        %h2.Reason_box__headline
          %span.Reason_box__headline--blue> 3分
          ですぐに出品
        %p.Reason_box__text スマホで入力するだけで簡単に出品できる！
      .Reason_box
        .Reason_box__image_box
          = image_tag 'pict/pict-reason-02.jpg', class: "Reason_box__image_box__img"
          .Reason_box__image_box__number 2
        %h2.Reason_box__headline
          %span.Reason_box__headline--blue> シンプル
          で使いやすい
        %p.Reason_box__text めんどくさい入力は必要なく、検索も購入もスムーズ！
      .Reason_box
        .Reason_box__image_box
          = image_tag 'pict/pict-reason-03.jpg', class: "Reason_box__image_box__img"
          .Reason_box__image_box__number 3
        %h2.Reason_box__headline
          手数料
          %span.Reason_box__headline--blue 業界最安
        %p.Reason_box__text 最大3%でお得に出品&amp;購入！
  .strong_point_visual_wrapper
    .Strong_point_visual
      %h2.Strong_point_visual__headline 会員数日本一
      %p.Strong_point_visual__text
        FURIMAは、フリマアプリで最も人気。
        %br>/
        出品・購入回数も業界最多です！
        %br>/
        ほしかったあの商品に出会えるかもしれません。
      .Strong_point_visual__badge
        = link_to "#" do
          = image_tag 'badge/app_store_badge.png', class: "Main_visual__badge--apple", size: "180x53"
        = link_to "#" do
          = image_tag 'badge/google-play-badge.png', class: "Main_visual__badge--google", size: "180x53"
.Feature_section
  .Feature_section__wrapper
    %h2.feature_headline FURIMAの特徴
    .Feature_list
      .Feature_box
        = image_tag "icon/icon-01.png", class: "Feature_box__img"
        %h2.Feature_box__headline 簡単に売り買いできる
        %p.Feature_box__text スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .Feature_box
        = image_tag "icon/icon-03.png", class: "Feature_box__img"
        %h2.Feature_box__headline 売上金は即日振込みに対応
        %p.Feature_box__text 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .Feature_box
        = image_tag "icon/icon-04.png", class: "Feature_box__img"
        %h2.Feature_box__headline 様々な支払いに対応
        %p.Feature_box__text お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
.items_section
  .Item_block
    %h2.Item_block__headline ピックアップカテゴリー
    %h3.Item_block__subtitle 新規投稿商品
    .Item_block__lists
      = render partial: "items_list", collection: @new_items, as: "item"
.footer_visual_section
  .Footer_visual
    %h2.Footer_visual__headline だれでもかんたん、人生を変えるフリマアプリ
    %p.Footer_visual__text 今すぐ無料ダウンロード！
    .Footer_visual__badge
      = link_to "#" do
        = image_tag 'badge/app_store_badge.png', class: "Main_visual__badge--apple", size: "180x53"
      = link_to "#" do
        = image_tag 'badge/google-play-badge.png', class: "Main_visual__badge--google", size: "180x53"
= render partial: "footer"
= render partial: 'items/putting_up_btn'